export interface Patient {
    id: number,
    firstName: string,
    lastName: string,
    birthdate: Date,
    sex: string | undefined,
    phone?: string,
    email?: string,
    address?: string,
    city?: string,
    state?: string,
    zip?: string,
    country?: string,
    insurance?: string,
    pharmacy?: string
}

export const initPrimaryKey: number = 7810;

export let patients: Array<Patient> = [
    {
        id: 7804,
        firstName: 'Robert',
        lastName: 'Paulson',
        birthdate: new Date(1986, 10, 27),
        sex: 'm',
        phone: '555-1234',
        email: 'robert.paulson@example.com',
        address: '123 Main St',
        city: 'New York',
        state: 'NY',
        zip: '10001',
        country: 'USA',
        insurance: 'Aetna',
        pharmacy: 'CVS'
    },
    {
        id: 7805,
        firstName: 'Jack',
        lastName: 'Rupert',
        birthdate: new Date(1979, 7, 18),
        sex: 'm',
        phone: '555-5678',
        email: 'jack.rupert@example.com',
        address: '456 Elm St',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90001',
        country: 'USA',
        insurance: 'Blue Cross',
        pharmacy: 'Walgreens'
    },
    {
        id: 7806,
        firstName: 'Marla',
        lastName: 'Singer',
        birthdate: new Date(1990, 4, 26),
        sex: 'f',
        phone: '555-8765',
        email: 'marla.singer@example.com',
        address: '789 Oak St',
        city: 'Austin',
        state: 'TX',
        zip: '73301',
        country: 'USA',
        insurance: 'Cigna',
        pharmacy: 'Rite Aid'
    },
    {
        id: 7807,
        firstName: 'Tyler',
        lastName: 'Durden',
        birthdate: new Date(1999, 9, 15),
        sex: 'm',
        phone: '555-0153',
        email: 'tyler.durden@example.com',
        address: '537 Paper St',
        city: 'Bradford',
        state: 'DE',
        zip: '19808',
        country: 'USA',
        insurance: 'UnitedHealth',
        pharmacy: 'Publix'
    },
    {
        id: 7808,
        firstName: 'Chloe',
        lastName: 'Streep',
        birthdate: new Date(2009, 5, 22),
        sex: 'f',
        phone: '555-2468',
        email: 'chloe.streep@example.com',
        address: '246 Maple St',
        city: 'Seattle',
        state: 'WA',
        zip: '98101',
        country: 'USA',
        insurance: 'Humana',
        pharmacy: 'Bartell Drugs'
    },
    {
        id: 7809,
        firstName: 'Kyle',
        lastName: 'Reese',
        birthdate: new Date(2016, 5, 8),
        sex: 'm',
        phone: '555-1357',
        email: 'kyle.reese@example.com',
        address: '135 Cedar St',
        city: 'Chicago',
        state: 'IL',
        zip: '60601',
        country: 'USA',
        insurance: 'Kaiser',
        pharmacy: 'Osco'
    },
    {
        id: 7810,
        firstName: 'Sarah',
        lastName: 'Connor',
        birthdate: new Date(1985, 2, 12),
        sex: 'f',
        phone: '555-1111',
        email: 'sarah.connor@example.com',
        address: '101 Skynet Ave',
        city: 'San Francisco',
        state: 'CA',
        zip: '94101',
        country: 'USA',
        insurance: 'Anthem',
        pharmacy: 'CVS'
    },
    {
        id: 7811,
        firstName: 'Bruce',
        lastName: 'Wayne',
        birthdate: new Date(1972, 3, 17),
        sex: 'm',
        phone: '555-2222',
        email: 'bruce.wayne@example.com',
        address: '1007 Mountain Dr',
        city: 'Gotham',
        state: 'NJ',
        zip: '07001',
        country: 'USA',
        insurance: 'WayneCare',
        pharmacy: 'Walgreens'
    },
    {
        id: 7812,
        firstName: 'Diana',
        lastName: 'Prince',
        birthdate: new Date(1987, 6, 1),
        sex: 'f',
        phone: '555-3333',
        email: 'diana.prince@example.com',
        address: '200 Paradise Island',
        city: 'Themyscira',
        state: 'DC',
        zip: '20001',
        country: 'USA',
        insurance: 'AmazonCare',
        pharmacy: 'Rite Aid'
    },
    {
        id: 7813,
        firstName: 'Clark',
        lastName: 'Kent',
        birthdate: new Date(1978, 5, 18),
        sex: 'm',
        phone: '555-4444',
        email: 'clark.kent@example.com',
        address: '344 Clinton St',
        city: 'Metropolis',
        state: 'NY',
        zip: '10002',
        country: 'USA',
        insurance: 'MetLife',
        pharmacy: 'Publix'
    },
    {
        id: 7814,
        firstName: 'Peter',
        lastName: 'Parker',
        birthdate: new Date(1995, 7, 10),
        sex: 'm',
        phone: '555-5555',
        email: 'peter.parker@example.com',
        address: '20 Ingram St',
        city: 'Queens',
        state: 'NY',
        zip: '11375',
        country: 'USA',
        insurance: 'Empire',
        pharmacy: 'Bartell Drugs'
    },
    {
        id: 7815,
        firstName: 'Tony',
        lastName: 'Stark',
        birthdate: new Date(1970, 4, 29),
        sex: 'm',
        phone: '555-6666',
        email: 'tony.stark@example.com',
        address: '10880 Malibu Point',
        city: 'Malibu',
        state: 'CA',
        zip: '90265',
        country: 'USA',
        insurance: 'StarkCare',
        pharmacy: 'Osco'
    },
    {
        id: 7816,
        firstName: 'Natasha',
        lastName: 'Romanoff',
        birthdate: new Date(1984, 11, 22),
        sex: 'f',
        phone: '555-7777',
        email: 'natasha.romanoff@example.com',
        address: '1 Red Room',
        city: 'Volgograd',
        state: 'RU',
        zip: '400001',
        country: 'Russia',
        insurance: 'RedCare',
        pharmacy: 'Walgreens'
    },
    {
        id: 7817,
        firstName: 'Steve',
        lastName: 'Rogers',
        birthdate: new Date(2018, 6, 4),
        sex: 'm',
        phone: '555-8888',
        email: 'steve.rogers@example.com',
        address: '569 Leaman Place',
        city: 'Brooklyn',
        state: 'NY',
        zip: '11201',
        country: 'USA',
        insurance: 'ShieldCare',
        pharmacy: 'CVS'
    },
    {
        id: 7818,
        firstName: 'Wanda',
        lastName: 'Maximoff',
        birthdate: new Date(1989, 1, 10),
        sex: 'f',
        phone: '555-9999',
        email: 'wanda.maximoff@example.com',
        address: '13 Novi Grad',
        city: 'Sokovia',
        state: 'SK',
        zip: '50001',
        country: 'Sokovia',
        insurance: 'HexCare',
        pharmacy: 'Rite Aid'
    }
];