/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppHeader.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppSettings: typeof import('./components/AppSettings.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Details: typeof import('./components/Patient/Details.vue')['default']
    Editor: typeof import('./components/Patient/Editor.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Remove: typeof import('./components/Patient/Remove.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
